task:
  name: Test FreeBSD
  freebsd_instance:
    matrix:
      image_family: freebsd-11-3-snap
      image_family: freebsd-12-1-snap
  update_script: pkg update -f
  install_script: 
    - pkg install -y libpcap bash gsed gmake py37-pip
    - python -m pip install -r Tests/ExamplesTest/requirements.txt
  configure_script:
    - ./configure-freebsd.sh --default
  build_script:
    - gmake all
  test_script:
    - cd Tests/Packet++Test && Bin/Packet++Test
    - cd ../Pcap++Test && sudo Bin/Pcap++Test -n
    - ping -c 4 www.google.com
    - ifconfig
    - ping -c 4 -I 10.128.0.45 www.google.com
    - cd ../ExamplesTest && python -m pytest
